import Head from 'next/head'
import React, { useContext, useEffect, useState } from 'react'

import HeroComponent from '../components/home/hero.component'
import PopularApisComponent from '../components/apis/summary-apis.component'
import { LanguageContext } from '../context/language.context'
import { getPopularApis } from '../services/apis.service'
import InfoTad from '../components/home/info-tad.component'

export default function Home() {
  const [data, setData] = useState([])
  useEffect(() => {
    const getData = async () => {
      const res = await getPopularApis()
      setData(res)
    }
    getData()
    return () => { }
  }, [])

  const { t } = useContext<any>(LanguageContext)
  return (
    <div>
      <Head>
        <title>{t.app.displayName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <HeroComponent />
        <InfoTad />
        <PopularApisComponent pupularApis={data} />
      </main>
    </div>
  )
}
