import Head from 'next/head';
import HeroComponent from '../components/home/hero.component';
import PopularApisComponent from '../components/popular-apis.component';
import { getPopularApis } from '../services/apis.service';

export default function Home({ pupularApis }: any) {
  return (
    <div>
      <Head>
        <title>Developer Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroComponent />
        <PopularApisComponent pupularApis={pupularApis} />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const data = await getPopularApis();

  return {
    props: {
      pupularApis: data,
    },
  };
}
